### PR TITLE
[API-675] Show tag/resource descriptions

### PR DESCRIPTION
**Pull request by billkauf**
https://pagerduty.atlassian.net/browse/API-675

Show the tag name and description at the top of each section.

image

This may need some stylin'...

### CODE REVIEW

**Comment by brhou** [comment]
Could you take a stab at the styling to make it look like something below?

**Comment by billkauf** [comment]
Better?

image

**Comment by brhou** [comment]
Better. the title font is still a little off. Also, is there a way to get a url anchor when you click on `Log Entries`?

screen shot 2016-02-24 at 3 17 14 pm

**Comment by billkauf** [comment]
I'm not sure I can catch clicks on the header, because it doesn't exist.

Check the HTML: it's just an enclosing `<div>` with a `label` attribute. Clicks on that are the same as clicks on the first operation.

**Comment by billkauf** [comment]
OK, now they're identical:

image

**Comment by brhou** [comment]
Looks good! I think that it would be a better experience if its anchorable, otherwise the users won't really ever stumble upon it. I could file it as another ticket if you'd like.

**Comment by billkauf** [comment]
I'll file a new ticket and claim it, just so this can go out now...

**Comment by brhou** [comment]
SGTM. Thanks!

**Comment by billkauf** [comment]
Opened [API-682](https://pagerduty.atlassian.net/browse/API-682) for clicking the tag name.

**Pull request merged**
